export const genres = [
  { value: "", label: "Escolha um gênero" },
  { value: "acao", label: "Ação e Aventura" },
  { value: "arte", label: "Arte e Fotografia" },
  { value: "biografia", label: "Biografia" },
  { value: "ciencia", label: "Ciência" },
  { value: "ciencia_politica", label: "Ciência Política" },
  { value: "classicos", label: "Clássicos" },
  { value: "contos_cronicas", label: "Contos e Crônicas" },
  { value: "culinaria", label: "Culinária" },
  { value: "direito", label: "Direito" },
  { value: "economia", label: "Economia" },
  { value: "educacao", label: "Educação" },
  { value: "ensaios", label: "Ensaios" },
  { value: "espiritualidade", label: "Espiritualidade" },
  { value: "fantasia", label: "Fantasia" },
  { value: "ficcao_cientifica", label: "Ficção Científica" },
  { value: "ficcao_historica", label: "Ficção Histórica" },
  { value: "filosofia", label: "Filosofia" },
  { value: "geografia_viagem", label: "Geografia e Viagem" },
  { value: "historia", label: "História" },
  { value: "historia_quadrinhos", label: "História em Quadrinhos" },
  { value: "horror_terror", label: "Horror e Terror" },
  { value: "humor", label: "Humor" },
  { value: "infantojuvenil", label: "Infantojuvenil" },
  { value: "informatica_tecnologia", label: "Informática e Tecnologia" },
  { value: "jornalismo", label: "Jornalismo" },
  { value: "linguistica", label: "Linguística" },
  { value: "literatura_erotica", label: "Literatura Erótica" },
  { value: "literatura_lgbt", label: "Literatura LGBT+" },
  { value: "medicina_saude", label: "Medicina e Saúde" },
  { value: "memorias", label: "Memórias" },
  { value: "misterio_detetive", label: "Mistério e Detetive" },
  { value: "moda", label: "Moda" },
  { value: "musica", label: "Música" },
  { value: "nao_ficcao", label: "Não-ficção" },
  { value: "natureza_ecologia", label: "Natureza e Ecologia" },
  { value: "negocios_economia", label: "Negócios e Economia" },
  { value: "poesia", label: "Poesia" },
  { value: "psicologia", label: "Psicologia" },
  { value: "religiao", label: "Religião" },
  { value: "romance", label: "Romance" },
  { value: "sociologia", label: "Sociologia" },
  { value: "suspense_thriller", label: "Suspense e Thriller" },
  { value: "teatro", label: "Teatro" },
  { value: "turismo", label: "Turismo" },
];
