export const genres = [
  { value: "", label: "Escolha um gênero" },
  { value: "acao", label: "Ação e Aventura" },
  { value: "arte", label: "Arte e Fotografia" },
  { value: "biografia", label: "Biografia" },
  { value: "ciencia", label: "Ciência" },
  { value: "ciencia_politica", label: "Ciência Política" },
  { value: "classicos", label: "Clássicos" },
  { value: "contos_cronicas", label: "Contos e Crônicas" },
  { value: "culinaria", label: "Culinária" },
  { value: "direito", label: "Direito" },
  { value: "economia", label: "Economia" },
  { value: "educacao", label: "Educação" },
  { value: "ensaios", label: "Ensaios" },
  { value: "espiritualidade", label: "Espiritualidade" },
  { value: "fantasia", label: "Fantasia" },
  { value: "ficcao_cientifica", label: "Ficção Científica" },
  { value: "ficcao_historica", label: "Ficção Histórica" },
  { value: "filosofia", label: "Filosofia" },
  { value: "geografia", label: "Geografia e Viagem" },
  { value: "historia", label: "História" },
  { value: "hq´s", label: "História em Quadrinhos" },
  { value: "horror_terror", label: "Horror e Terror" },
  { value: "humor", label: "Humor" },
  { value: "infantojuvenil", label: "Infantojuvenil" },
  { value: "informatica_tecnologia", label: "Informática e Tecnologia" },
  { value: "jornalismo", label: "Jornalismo" },
  { value: "linguistica", label: "Linguística" },
  { value: "literatura_erotica", label: "Literatura Erótica" },
  { value: "literatura_lgbt", label: "Literatura LGBT+" },
  { value: "medicina", label: "Medicina e Saúde" },
  { value: "misterio_detetive", label: "Mistério e Detetive" },
  { value: "moda", label: "Moda" },
  { value: "musica", label: "Música" },
  { value: "nao_ficcao", label: "Não-ficção" },
  { value: "natureza_ecologia", label: "Natureza e Ecologia" },
  { value: "negocios_economia", label: "Negócios e Economia" },
  { value: "poesia", label: "Poesia" },
  { value: "psicologia", label: "Psicologia" },
  { value: "religiao", label: "Religião" },
  { value: "romance", label: "Romance" },
  { value: "sociologia", label: "Sociologia" },
  { value: "suspense_thriller", label: "Suspense e Thriller" },
  { value: "teatro", label: "Teatro" },
  { value: "turismo", label: "Turismo" },
];

export const fanficGenres = [
  { value: "", label: "Escolha um gênero" },
  { value: "acao_policial", label: "Ação/Policial" },
  { value: "angst_profundo", label: "Angst Profundo" },
  { value: "au_fantasia", label: "AU de Fantasia" },
  { value: "au_futurista", label: "AU Futurista" },
  { value: "au_historico", label: "AU Histórico" },
  { value: "aventura_epica", label: "Aventura Épica" },
  { value: "comedia_pastelao", label: "Comédia Pastelão" },
  { value: "comedia_romantica", label: "Comédia Romântica" },
  { value: "comedia_situacao", label: "Comédias Sitcom" },
  { value: "crossover_multicultural", label: "Multicultural" },
  { value: "drama_familiar", label: "Drama Familiar" },
  { value: "drama_guerra", label: "Drama de Guerra" },
  { value: "fantasia_dark", label: "Fantasia Dark" },
  { value: "fantasia_urbana", label: "Fantasia Urbana" },
  { value: "ficcao_espacial", label: "Ficção Científica Espacial" },
  { value: "fluff_familiar", label: "Fluff Familiar" },
  { value: "horror_lovecraftiano", label: "Horror Lovecraftiano" },
  { value: "horror_psicologico", label: "Horror Psicológico" },
  { value: "horror_sobrenatural", label: "Horror Sobrenatural" },
  { value: "hurt_psicologico", label: "Hurt Psicológico" },
  { value: "informatica_tecnologia", label: "Informática e Tecnologia" },
  { value: "life_escolar", label: "Slice of Life Escolar" },
  { value: "misterio_thriller", label: "Mistério/Thriller" },
  { value: "realismo_magico", label: "Realismo Mágico" },
  { value: "romance_classico", label: "Romance Clássico" },
  { value: "romance_lgbtq", label: "Romance LGBTQ+" },
  { value: "romance_sobrenatural", label: "Romance Sobrenatural" },
  { value: "sci_fi_cyberpunk", label: "Sci-Fi Cyberpunk" },
  { value: "super_herois", label: "Super-heróis" },
];
